# Generated by Django 5.0.6 on 2024-05-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projekcija',
            name='Duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projekcija',
            name='Seats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projekcija',
            name='MovieName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
