# Generated by Django 5.0.6 on 2024-06-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_roles_student_delete_karta_delete_projekcija'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='surname',
            new_name='lastname',
        ),
    ]
