# Generated by Django 5.0.6 on 2024-06-03 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'administrator'), ('prof', 'profesor'), ('stu', 'student')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('izv', 'izvanredni student'), ('red', 'redovni student')], default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='admin', null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.uloge'),
        ),
    ]
