# Generated by Django 5.0.6 on 2024-06-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('none', 'None'), ('izv', 'izvanredni student'), ('red', 'redovni student')], default='none', max_length=20),
        ),
        migrations.DeleteModel(
            name='Uloge',
        ),
    ]
