# Generated by Django 5.0.6 on 2024-06-03 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_user_role_alter_user_status_delete_uloge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'administrator'), ('prof', 'profesor'), ('stu', 'student')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.uloge'),
        ),
    ]
