# Generated by Django 5.0.6 on 2024-06-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_alter_user_role_delete_uloge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'administrator'), ('prof', 'profesor'), ('stu', 'student')], max_length=20),
        ),
    ]
