# Generated by Django 5.0.6 on 2024-06-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_user_role_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ime', models.CharField(max_length=50)),
                ('Kod', models.CharField(max_length=50)),
                ('Program', models.CharField(max_length=50)),
                ('ECTS', models.IntegerField()),
                ('sem_red', models.IntegerField()),
                ('sem_izv', models.IntegerField()),
                ('izborni', models.CharField(choices=[('da', 'da'), ('ne', 'ne')], max_length=50)),
                ('nositelj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
