# Generated by Django 5.0.6 on 2024-06-06 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_predmeti'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('izv', 'izvanredni student'), ('red', 'redovni student')], default='none', max_length=20),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('enrolled', 'Enrolled'), ('passed', 'Passed'), ('failed', 'Failed'), ('lost_right', 'Lost the Right to Pass')], default='enrolled', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.predmeti')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='enrolled_subjects',
            field=models.ManyToManyField(related_name='enrolled_students', through='app1.Enrollment', to='app1.predmeti'),
        ),
    ]
