# Generated by Django 5.0.6 on 2024-06-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_user_status_enrollment_user_enrolled_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled')], default='enrolled', max_length=20),
        ),
    ]
