# Generated by Django 5.0.6 on 2024-06-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('pass', 'Passed'), ('fail', 'Failed')], default='enrolled', max_length=20),
        ),
    ]
